# Generated by Django 4.2.3 on 2023-12-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus_final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
