# Generated by Django 4.2.3 on 2023-12-31 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus_final', '0003_driverlocation_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits is allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
