# Generated by Django 4.2.3 on 2024-01-01 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bus_final', '0005_remove_driverlocation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
